import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:freeu/common/bullet_text_bold.dart';
import 'package:freeu/common/customNextButton.dart';
import 'package:freeu/common/signupAppbar.dart';
import 'package:freeu/common/sized_box.dart';
import 'package:get/get.dart';
import 'package:getwidget/getwidget.dart';

class AlternativeCategories2 extends StatefulWidget {
  const AlternativeCategories2({super.key});

  @override
  State<AlternativeCategories2> createState() => _AlternativeCategories2State();
}

class _AlternativeCategories2State extends State<AlternativeCategories2> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CustomSignupAppBar(
        titleTxt: "",
        bottomtext: false,
      ),
      bottomNavigationBar: Padding(
        padding: EdgeInsets.fromLTRB(16.w, 5.h, 16.w, 10.h),
        child: CustomNextButton(
          text: 'View Categories deals',
          ontap: () {
            Get.toNamed("/VerticalSlider");

            // Get.toNamed("/privateequity");
          },
        ),
      ),
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: 16.w),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.start,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Flexible(
                  child: Text(
                    "Alternative Investment Funds Category II",
                    style: TextStyle(
                        fontFamily: "Poppins",
                        fontSize: 25.sp,
                        fontWeight: FontWeight.w500),
                  ),
                ),
              ],
            ),
            Expanded(
                child: SingleChildScrollView(
              child: Column(
                children: [
                  sizedBoxHeight(20.h),
                  faqAccod(
                    title: 'Introduction to Category II AIF',
                    content:
                        'As per SEBI Regulations Category II AIF are AIFs which does not fall in Category I and III and which do not undertake leverage or borrowing other than to meet day-to-day operational requirements. The government or the regulator does not offer any concessions or incentives for these funds. Private equity funds or debt funds are examples of Category II AIFs. This category comprises 80% AIFs and is the most popular among AIFs.',
                  ),
                  sizedBoxHeight(20.h),
                  faqAccod(
                    title: 'Funds under Category II AIF',
                    content:
                        '> Private Equity (PE) Fund\n>	Debt Fund\n>	Private Real Estate Fund\n>	Fund for Distressed Assets,',
                  ),
                  sizedBoxHeight(20.h),
                  faqAccodHighlight(),
                  sizedBoxHeight(20.h),
                  faqAccod(
                    title: 'Taxation',
                    content:
                        "Category I and II Alternative Investment Funds (AIFs) are granted tax pass-through status by the government. This implies that any income generated by the fund, excluding business income, is taxed to the investor based on their share of income from the AIF, similar to if they had directly made the investment. Accordingly, business income of Category I and II AIFs is taxed at the fund level at the maximum marginal rate, while dividends, capital gains, or interest earned by the AIF are taxed at the investor's level according to their tax slab. "
                        '\n\nInvestors in Category I and II AIFs are required to pay capital gain tax on profits or losses, depending on the duration of their investment. Long-term capital gain tax is levied at 20% with an indexation benefit, and short-term capital gains are taxed at 15%. The surcharge and education cess are applicable in addition to the aforementioned rates. Furthermore, non-resident investors can avail a beneficial tax rate of 10% for long-term capital gains arising from the transfer of unlisted securities or shares of a company not substantially interested by the public, subject to certain conditions. However, indexation and foreign exchange fluctuation benefits are not available in this case.',
                  ),
                  sizedBoxHeight(20.h),
                ],
              ),
            )),
          ],
        ),
      ),
    );
  }

  Widget faqAccod(
      {bool? expandAccod, required String title, required String content}) {
    return Container(
      decoration: BoxDecoration(
          border: Border.all(color: Colors.black.withOpacity(0.2)),
          color: Colors.white,
          borderRadius: BorderRadius.circular(5.r)),
      child: GFAccordion(
        showAccordion: expandAccod ?? false,
        titleBorderRadius: BorderRadius.circular(5.r),
        contentBorderRadius: BorderRadius.only(
          bottomLeft: Radius.circular(5.r),
          bottomRight: Radius.circular(5.r),
        ),
        margin: const EdgeInsets.all(0),
        titlePadding: EdgeInsets.all(10.h),
        contentPadding: EdgeInsets.all(10.w),
        expandedTitleBackgroundColor: Colors.white,
        contentBackgroundColor: Colors.white,
        titleChild: Text(
          title,
          style: TextStyle(
              color: Colors.black,
              fontSize: 20.sp,
              fontFamily: "Poppins",
              fontWeight: FontWeight.w500),
        ),
        contentChild: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Container(
                  color: Colors.brown,
                  height: 1,
                  width: MediaQuery.of(context).size.width / 1.65,
                ),
                Container(
                  decoration: BoxDecoration(
                      color: Colors.brown,
                      borderRadius: BorderRadius.circular(100.r)),
                  height: 8,
                  width: 8,
                )
              ],
            ),
            sizedBoxHeight(15.h),
            Text(
              content,
              style: TextStyle(
                color: Colors.black,
                fontFamily: "Poppins",
                fontSize: 16.sp,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget faqAccodHighlight() {
    List bulletPoints = [
      {
        "title": "Primary Investment Focus: ",
        "desp":
            'Category II AIFs invest primarily in unlisted companies directly or through investments in units of other AIFs.',
      },
      {
        "title": 'Hedging Activities: ',
        "desp":
            'Category II AIFs may engage in activities such as hedging, which includes credit default swaps.',
      },
      {
        "title": 'Restrictions on Borrowing and Leverage: ',
        "desp":
            'Category II AIFs are not permitted to borrow funds directly or indirectly or engage in any form of leverage, except for meeting temporary funding requirements.',
      },
      {
        "title": 'Tenure: ',
        "desp":
            'The minimum fund tenure for Category II AIFs is 3 years The fund tenure can be extended by two years subject to the approval of two-third of the investors.',
      },
      {
        'title': 'Investment Limit: ',
        'desp':
            'Category II AIFs are allowed to invest not more than 25% of the investible funds in a Single Portfolio Entity.',
      },
      {
        'title': 'Manager/Sponsor Interest: ',
        'desp':
            'The manager/sponsor interest should be the lower of the following amounts 2.5% of the corpus or INR 5 crore.',
      },
    ];

    return Container(
      decoration: BoxDecoration(
          border: Border.all(color: Colors.black.withOpacity(0.2)),
          color: Colors.white,
          borderRadius: BorderRadius.circular(5.r)),
      child: GFAccordion(
        showAccordion: false,
        titleBorderRadius: BorderRadius.circular(5.r),
        contentBorderRadius: BorderRadius.only(
          bottomLeft: Radius.circular(5.r),
          bottomRight: Radius.circular(5.r),
        ),
        margin: const EdgeInsets.all(0),
        titlePadding: EdgeInsets.all(10.h),
        contentPadding: EdgeInsets.all(10.w),
        expandedTitleBackgroundColor: Colors.white,
        contentBackgroundColor: Colors.white,
        titleChild: Text(
          "General guidelines for Category II AIFs",
          style: TextStyle(
              color: Colors.black,
              fontSize: 20.sp,
              fontFamily: "Poppins",
              fontWeight: FontWeight.w500),
        ),
        contentChild: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.start,
              children: [
                Container(
                  color: const Color(0xFF143C6D),
                  height: 1,
                  width: MediaQuery.of(context).size.width / 1.65,
                ),
                Container(
                  decoration: BoxDecoration(
                      color: const Color(0xFF143C6D),
                      borderRadius: BorderRadius.circular(100.r)),
                  height: 8,
                  width: 8,
                )
              ],
            ),
            sizedBoxHeight(16.h),
            Text(
              'Category II AIFs have certain guidelines that they must follow which are essential to ensure that they operate within the legal framework and meet the requirements set forth by the regulatory authorities. Here are some of the key guidelines that Category II AIFs must adhere to',
              style: TextStyle(
                color: Colors.black,
                fontFamily: "Poppins",
                fontSize: 16.sp,
              ),
            ),
            ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: bulletPoints.length,
                itemBuilder: (context, index) {
                  return bulletTextBoldTitle(
                      title: bulletPoints[index]["title"],
                      text: bulletPoints[index]["desp"]
                      // /
                      );
                }),
          ],
        ),
      ),
    );
  }

}
